### ISSUE TITLE
Breaks on destructured args

### ISSUE THREAD

**Issue by keenahn** [tunnckoCore/parse-function#32]
```js
> const parseFn = require('parse-function')
> const app = parseFn({ ecmaVersion: 2017 })
> const b = ({a, b, c}) => a + b + c
undefined
> app.parse(b)
{ name: null,
  body: 'a + b + c',
  args: [ false ],
  params: 'false' }
```

Any plans on incorporating this in the future? 

```
Node: 8.1.4
```

**Comment by tunnckoCore** [comment]
What may be the expected result? I really starting to not like such cases, especially in that package :D It's a bit hard to decide, in first place. And in second, it is one single argument without a name.

It may be implemented of course, it's not that hard, since that's just AST and that package support plugins. It can be, but it's a bit confusing what the result should be, and if not that, it may be confusing for others - the end users, if there are much to think. Because now, `params` is just a string with comma-separated names.

But if we implement something i see it that way: `params: '{a, b, c}, foo'` for `({a, b, c}, foo) => {}`, nothing more than that, imo.

I believe best way is to create a plugin and we can link it from the README :) If there are some questions about that API, ask :)

**Comment by tunnckoCore** [comment]
In any way, pull requests are welcome if we can think for some good end result. But again, I prefer to not add too much when there is plugin API and because it already has pretty good support of (ES6) features.

**Comment by keenahn** [comment]
No problem. I'll think about implementation as a plugin. BTW, do you have a list of known plugins? :)

**Comment by tunnckoCore** [comment]
Great! Ping me with `@charlike` or `@tunnckoCore` (because i'm thinking of some github/npm changes ;d) when/if you make some plugin, so i'll link it :)

No, for now we don't have other plugins :)

Very thanks for the interest!

**Comment by tunnckoCore** [comment]
hey! ;wave: it would be awesome if you create a plugin! Please feel free to open a PR for adding it in the readme :)
