### ISSUE TITLE
Functions containing GREATER_THAN are parsed incorrectly

### ISSUE THREAD

**Issue by eush77** [tunnckoCore/parse-function#5]
``` js
> parseFunction(function (a, b) { return a > b })
{ name: 'anonymous',
  body: ' ',
  params: 'unction (a, b) { return ',
  args: [ 'unction (a', 'b) { return ' ] }
```

Functions that contain `>` character are loosely [considered](https://github.com/tunnckoCore/parse-function/blob/302a965ef391aadb705ba3c63ca2d9c95d2a7e3d/index.js#L81) arrow functions in `walk`, and later in `build` function `params` and `args` properties are [computed](https://github.com/tunnckoCore/parse-function/blob/302a965ef391aadb705ba3c63ca2d9c95d2a7e3d/index.js#L148-L149) incorrectly because of that. I'm not sure how you would fix that.

**Comment by tunnckoCore** [comment]
Aaaand yes, problems start appearing, haha - normal. But that's the interesting, I like to play this game and experimenting and learn new things.

Thanks for the report, I'll review what I can do.

Cheers,
Charlike.

**Comment by tunnckoCore** [comment]
Actually, when i built `walk` that way i though to check prev `ch` for `=` which would be the correct way.
I reviewed few parsers and have some idea.

We need strongly to implement benchmark tests. If it is slower, then we can return to `regex`, otherwise we will stay that way and will try to fix every new issue.
